# One source of truth: editable assets also supply the built-in fallback.
foreach(page IN ITEMS now_playing technical_status)
    if(page STREQUAL "now_playing")
        set(asset_name player)
    else()
        set(asset_name status)
    endif()
    set(generated "")
    foreach(ext IN ITEMS html css js)
        set(asset "${CMAKE_CURRENT_SOURCE_DIR}/ui/default/${asset_name}.${ext}")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${asset}")
        file(READ "${asset}" contents)
        string(FIND "${contents}" ")PICD_UI\"" delimiter)
        if(NOT delimiter EQUAL -1)
            message(FATAL_ERROR "UI asset contains reserved raw-string delimiter: ${asset}")
        endif()
        set(suffix ${ext})
        if(ext STREQUAL "js")
            set(suffix javascript)
        endif()
        string(APPEND generated "std::string_view ${page}_${suffix}() { return R\"PICD_UI(${contents})PICD_UI\"; }\n")
    endforeach()
    # COPYONLY avoids treating user-authored @text@ or $<...> as CMake syntax.
    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/${page}_assets.tmp" "${generated}")
    configure_file("${CMAKE_CURRENT_BINARY_DIR}/${page}_assets.tmp"
                   "${CMAKE_CURRENT_BINARY_DIR}/${page}_assets.inc" COPYONLY)
endforeach()
